---
title: "R codes for Ch 16: Sampling Distribution Models and Confidence Intervals for Proportions"
author: "Dr. Hasthika Rupasinghe"
date: '`r format(Sys.time(), "%b %d, %Y at %X")`'
output:
  bookdown::html_document2:
    toc: true
    toc_depth: 2
    highlight: textmate
    theme: yeti
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.align = "center", comment = NA)
#library(tidyverse)
```





***
# Simulation of proportion with graphs

We use this section of the RScript to understand the concept of Sampling Distribution (of the Proportion). Do not use this part to solve problems.

```{r}

p <- .6 # Actual population proportion of females
n <- 30 # Sample size

# Generate a sample
sample <- sample(c(0,1), size = n, replace = TRUE, prob=c(1-p,p)) 

# Looking at the sample (optional)
sample 

# Find the proportion of females (phat for this sample)
sum(sample)/n


# Now repeat the above process 1000 times and find the average of proportions

phat <- numeric(1000)

for (i in 1:1000){
  
  sample <- sample(c(0,1), size = n, replace = TRUE, prob=c(1-p,p)) 
  phat[i] <- sum(sample)/n 
}


hist(phat) # Shape

mean(phat) # Center
sd(phat)   # Spread


# End of simulation
```

***

# Using the theoretical distribution to solve problems

## Check conditions

```{r}

p <- 0.15# Population Proportion of interest
n <- 200 # Sample size 

#Check assumptions!!!
n*p > 10
n*(1-p) > 10


# Mean and the sd of the sampling distribution for phat
meanphat <- p
sdphat<- sqrt(p*(1-p)/n)

meanphat
sdphat

```

## Answring probability problems

```{r}

#less than for a normal
#pnorm(value,mean,sd)

pnorm(.06,meanphat,sdphat)

#greater than for a normal
#1-pnorm(value,mean,sd)

1-pnorm(0.12,meanphat,sdphat)

#between for a normal
#pnorm(bigvalue,mean,sd)-pnorm(smallerval,mean,sd)

pnorm(.12,meanphat,sdphat)-pnorm(.08,meanphat,sdphat)

# Given the probability find the quantile
#qnorm(percentless,mean,sd)

qnorm(.9,meanphat,sdphat)

```

***

# Confidence Intervals For proportion 

```{r}
#######################################
# Confidence Intervals For proportion #
#######################################

x <- 66 # successes
n <- 97 # trials
phat <- x/n

CIlev <- 0.90 # CI Level as a decimal
alpha <- 1-CIlev
alphaovertwo <- alpha/2
oneminusalphaovertwo <- 1- alpha/2
zstar <- qnorm(oneminusalphaovertwo) 

cat("Your Critical value (z*) is =", zstar, "\n")


#ME <- zstar * sqrt(phat* (1-phat)/n) # If you are only looking for the ME, remove the pound signs and run these two lines
#ME

LowP <- phat - zstar * sqrt(phat* (1-phat)/n) # Lower limit of the CI
UpP <- phat + zstar * sqrt(phat *(1-phat)/n) # Upper limit of the CI

CI <- c(LowP,UpP)

cat("The asymptotic", CIlev*100, " % confidence interval for p is", CI) 
```

#  Solve for sample size


You write it!

