---
title: "R codes for Ch 18"
author: "Dr. Hasthika Rupasinghe"
date: '`r format(Sys.time(), "%b %d, %Y at %X")`'
output:
  bookdown::html_document2:
    highlight: textmate
    theme: yeti
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.align = "center", comment = NA)
library(tidyverse)
```

# Confidance Intervals For proportion

```{r}

#######################################
# Confidence Intervals For proportion #
#######################################

x <- 66 # successes
n <- 97 # trials
phat <- x/n

CIlev <- 0.90 # CI Level as a decimal
alpha <- 1-CIlev
alphaovertwo <- alpha/2
oneminusalphaovertwo <- 1- alpha/2
zstar <- qnorm(oneminusalphaovertwo) 

cat("Your Critical value (z*) is =", zstar, "\n")


#ME <- zstar * sqrt(phat* (1-phat)/n) # If you are only looking for the ME, remove the pound signs and run these two lines
#ME

LowP <- phat - zstar * sqrt(phat* (1-phat)/n) # Lower limit of the CI
UpP <- phat + zstar * sqrt(phat *(1-phat)/n) # Upper limit of the CI

CI <- c(LowP,UpP)

cat("The asymptotic", CIlev*100, " % confidence interval for p is", CI) #concatenate
```


## Critical value (z*)

```{r}

#####################################
# Critical value (z*)               #
#####################################

CIlev <- .98 # Level as a decimal


alpha <- 1-CIlev
alphaovertwo <- alpha/2
oneminusalphaovertwo <- 1- alpha/2

zstar <- qnorm(oneminusalphaovertwo) 

zstar

```


# Sample size


```{r}

#############################
#  Solve for sample size:   #
#############################


phatstar <-  0.5 # use .5 if not given in the problem
ME <-  0.09 # Margin of error 
CIlev <- .99 # CI level

alpha <- 1-CIlev
alphaovertwo <- alpha/2
oneminusalphaovertwo <- 1- alpha/2
zstar <- qnorm(oneminusalphaovertwo)

n <- (zstar/ME)^2*phatstar*(1-phatstar)


cat("The required sample size is ",ceiling(n))  #ceiling function always goes up to the next integer
```


# Solve for confidence level

Example: Ch18 HW2:
A newspaper reports that the governor's approval rating stands at 49\%. The article adds that the poll is based on a random sample of 3392 adults and has a margin of error of 2\%. What level of confidence did the pollsters use?



```{r}
##############################
# Solve for confidence level :
##############################

ME <- .02
n <- 3392
phat <- .49

zsolved <- ME *sqrt(n/(phat*(1-phat)))

arealess <- pnorm(zsolved)

Conf <- (1 - 2*(1-arealess))*100

cat("This is a ",Conf,"% confidence interval.")

```

#  Solve for sample size

You write it!