---
title: "R codes for Ch 20"
author: "Dr. Hasthika Rupasinghe"
date: '`r format(Sys.time(), "%b %d, %Y at %X")`'
output:
  bookdown::html_document2:
    toc: yes
    highlight: textmate
    theme: yeti
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.align = "center", comment = NA)
library(tidyverse)
```




# CI for single mean $\mu$

```{r}
times <- c(10.2,6,12.2,6,6,13.5,9.5,11.2,9.1,14.7)

ybar <- mean(times)#12.5
s <- sd(times)#2
n <- length(times)#25
CIlev <- .95


df <- n-1

alpha <- 1-CIlev
alphaovertwo <- alpha/2
oneminusalphaovertwo <- 1- alpha/2
tstar <- qt(oneminusalphaovertwo,df)

tstar #t in a CI formula

LowMu <- ybar - tstar * s/sqrt(n)
UpMu <- ybar + tstar * s/sqrt(n)

CI <- c(LowMu, UpMu)

cat("The ", CIlev*100, " % confidence interval for mu is", CI)
```

# Testing Hypotheses about mean $\mu$

#### Step 0:  Find(or enter) the sample mean ($\bar{y}$) and standard deviation ($s$) and $n${-}

```{r}
ybar <- 12.5
s <- 2

n <- 25
```


#### Step 1:  Formulate Hypotheses (PARAMETERS) {-}

```{r}
#Step 1:  Formulate Hypotheses (PARAMETERS)

mu0 <- 10 #This is the value in H0 : mu = mu0
```


#### Step 2:  Calcualte the standardized test statistic {-}
```{r}
# Step 2:  Calcualte the standardized test statistic
tstat <- 1.76 #(ybar - mu0)/(s/sqrt(n))

cat("The t-stat is",tstat)
```

#### Step 3:  Calcualte the P-value {-}

```{r}
#P-value = P(get what you got or more when Ho is true)

df <- 24 #n - 1 # degrees of freedom

#less
LTPval<- pt(tstat,df)

#more
GTPval<- 1-pt(tstat,df)

#not equal
NEPval <- 2*pt(-abs(tstat), df)

list(Less=LTPval,Greater=GTPval,NotEqual=NEPval)

```

#### Step 4: Conclusion {-}
```{r}
#Statistical conclusion: A) Reject Ho if P-val < alpha (use .05 if none given)
#                         B) Fail to reject Ho if P-val > alpha

#English conclusion: A) There IS evidence of Ha (written to match problem)
#                     B) There is NOT evidence of Ha.

# End of Hypotheses about the mean
```


# Sample size to estimate $\mu$ within a given ME



```{r}
CIlev <- .95
s <- 29.31
ME <- 0.02

alpha <- 1-CIlev
alphaovertwo <- alpha/2
oneminusalphaovertwo <- 1- alpha/2
zinCI <- qnorm(oneminusalphaovertwo)

nprelim <- (zinCI * s/ME)^2
df <- nprelim-1

tstar <- qt(oneminusalphaovertwo,df)

nfinal <- (tstar * s/ME)^2
ceiling(nfinal)
```

# Graphs to check if a given data set is nearly normal 

```{r}

myData <- c(10.26, 10.35,  8.12, 13.21, 11.52, 12.26,  8.15,  7.71,  7.29, 10.93, 10.91,  6.54, 11.16,  9.92,  9.19,  6.93, 12.04,  9.55, 14.07, 10.03)

# Methods I: Histogram - If the graph look symmetric and bell shaped data is nearly normal 

hist(myData)

# Methods II: QQ plot - If the plotted points follow the identity line, data is nearly normal 

qqnorm(myData)

```

