---
title: "R codes for Ch 22: Two Means"
author: "Dr. Hasthika Rupasinghe"
date: '`r format(Sys.time(), "%b %d, %Y at %X")`'
output:
  bookdown::html_document2:
    toc: true
    highlight: textmate
    theme: yeti
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.align = "center", comment = NA)
library(tidyverse)
```

> **_NOTE:_**  Use this script for Ch22 ONLY if the question talks about two means

# Checking assumptions

  1) Independent data
  2) Randomization
  3) Less than 10\% of the population is in the sample
  5) Independent Groups

If assumptions are met, $\bar{x_1} - \bar{x_2} \sim N(\mu_1-\mu_2, \sqrt{(s_1^2/n_1 +s_2^2/n_2)})$

# CI for $\mu_1-\mu_2$

```{r}
ybar1 <- 80
s1 <- 5
n1 <- 26

ybar2 <- 74
s2 <- 6
n2 <- 32

df <- (s1^2/n1 +s2^2/n2)^2/(1/(n1-1)*(s1^2/n1)^2 + 1/(n2-1)*(s2^2/n2)^2)

CIlev <- .95

alpha <- 1-CIlev
alphaovertwo <- alpha/2
oneminusalphaovertwo <- 1- alpha/2
tstar <- qt(oneminusalphaovertwo,df)

tstar  #tstar in a CI formula

LowP <- ybar1-ybar2 - tstar * sqrt(s1^2/n1 +s2^2/n2)
UpP <- ybar1-ybar2 + tstar * sqrt(s1^2/n1 +s2^2/n2)

CI <- c(LowP,UpP)

cat("The ", CIlev*100, " % confidence interval for mu is", CI)
  
```

# HT for $\mu_1-\mu_2$

```{r}
ybar1 <-80
s1 <- 5
n1<-26

ybar2 <-74
s2 <- 6
n2 <- 32

df <- (s1^2/n1 +s2^2/n2)^2/(1/(n1-1)*(s1^2/n1)^2 + 1/(n2-1)*(s2^2/n2)^2)

cat("Degees of freedom is", df, "\n")

tstat <- (ybar1-ybar2)/sqrt(s1^2/n1 +s2^2/n2)

cat("The t-stat is", tstat, "\n")

#less
LTPval<- pt(tstat, df)

#more
GTPval<- 1-pt(tstat, df)

#not equal
NEPval<-2*pnorm(-abs(tstat))


list(LessPval=LTPval,GreaterPval=GTPval,NotEqualPval=NEPval)
```


