---
title: "R codes for Ch 23: Paired Data"
author: "Dr. Hasthika Rupasinghe"
date: '`r format(Sys.time(), "%b %d, %Y at %X")`'
output:
  bookdown::html_document2:
    toc: true
    highlight: textmate
    theme: yeti
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.align = "center", comment = NA)
library(tidyverse)
```

> **_NOTE:_**  Use this script for Ch22 ONLY if the question talks about two dependent means


# CI

```{r}
PreCourseAnx <- c(7, 6, 9, 5, 6, 7, 5, 7, 6, 4, 3, 2, 1, 3, 4, 2)
PostCourseAnx <- c(4, 3, 7, 3, 4, 5, 4, 6, 5, 3, 2, 2, 1, 3, 4, 3)

d <-PreCourseAnx - PostCourseAnx
d

dbar <-mean(d)
sOfd <- sd(d)
nd <- length(d)

df <- nd-1

CIlev <- .90

alpha <- 1-CIlev
alphaovertwo <- alpha/2
oneminusalphaovertwo <- 1- alpha/2
tstar <- qt(oneminusalphaovertwo,df)

tstar #tstar in a CI formula

Low <- dbar - tstar * sOfd/sqrt(nd)
Up <- dbar + tstar * sOfd/sqrt(nd)

CI <- c(Low,Up)

cat("The ", CIlev*100, " % confidence interval for mu is", CI)
  
```

# HT 

```{r}
PreCourseAnx <- c(7, 6, 9, 5, 6, 7, 5, 7, 6, 4, 3, 2, 1, 3, 4, 2)
PostCourseAnx <- c(4, 3, 7, 3, 4, 5, 4, 6, 5, 3, 2, 2, 1, 3, 4, 3)

d <-PreCourseAnx - PostCourseAnx
d

dbar <-mean(d)
sOfd <- sd(d)
nd <- length(d)

df <- nd-1

HoMean <- 0

tstat <- (dbar-HoMean)/(sOfd/sqrt(nd))
tstat


#P-value = P(get what you got or more when Ha is true)

#less than
LTPval<-pt(tstat, df)
#greater than
GTPval<-1-pt(tstat, df)
#not equal
NEPval<-2*pt(-abs(tstat), df)


list(LessPval=LTPval,GreaterPval=GTPval,NotEqualPval=NEPval)
```


