---
title: "R codes for Ch 24"
author: "Dr. Hasthika Rupasinghe"
date: '`r format(Sys.time(), "%b %d, %Y at %X")`'
output:
  bookdown::html_document2:
    toc: true
    highlight: textmate
    theme: yeti
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.align = "center", comment = NA)
library(tidyverse)
```


# Intro: How does Chi-square distribution looks like.

```{r}
# Codes Optional
x <- seq(0,20,.1) #sequence from, to, by
fx <- dchisq(x,df=5) #density of a chisquare
plot(x,fx,type="l") #type = lines

```

# Test 1: Goodness of fit

```{r}

################################################################
# Test 1
# Goodness of fit = table matches what you expect...one variable 
# Ho:distribution matches stated
################################################################


# Example in the notes-  grades = "A", "B", "C", "D", "F"

obs <- c(89, 121, 78, 25, 12)
exppercent <- c(0.15, 0.3, 0.4, 0.1, 0.05)

results <- chisq.test(obs,p=exppercent)
results

```

# Test 2: Homogeneity

```{r}
################################################################
# Test 2
# Homogeneity = one variable, comparing groups to one another  
# Ho:  distribution same across groups
################################################################

shows <- matrix(c(50, 30, 20, 50, 80, 70), ncol=3, byrow=TRUE)
colnames(shows)<-c("Lone Ranger", "Sesame St", "The Simpsons")
rownames(shows)<-c("Boys", "Girls")

testtable <- as.table(shows)
testtable

chisq.test(testtable)
```

# Test 3: Independence

```{r}
################################################################
# Test 3
# Independence = two variables 
# Ho: no association between row and column
################################################################

meningitis <- matrix(c(30, 72, 2, 26),ncol=2,byrow=TRUE)
colnames(meningitis)<-c("Meningitis","Other")
rownames(meningitis)<-c("Light","Dark")

testtable <- as.table(meningitis)
testtable

chisq.test(testtable, correct=FALSE)
```


# Critical values for $\chi^2$ distribution 

  * If the test statistic (a $\chi^2$  test statistic in this case) falls to the right of the critical value we reject $H_o$
  * If the test statistic falls to the left of the critical value we fail to reject $H_o$

```{r}


alpha <- 0.01
df <- 3
critical_val <- qchisq(1-alpha, df)
critical_val


# Optional code to make a graph to visualize the rejection region (this graphic is not dynamic, only woks with the ex above)
ggplot(data.frame(x = c(0, 20)), aes(x = x, fill = x > critical_val)) +
     stat_function(fun = dchisq, args = list(df = 3)) +
  labs(xlab = " ", ylab = " ") +
  geom_vline(xintercept = critical_val)+
  annotate(geom="text", x=15, y=0.00, label="Rejection Region", color="red") +
  annotate(geom="text", x=5, y=0.00, label="Do not Reject Region", color="green") +
  annotate(geom="text", x=11, y=0.05, label="Critical Value", color="steelblue", angle = 90) +
  annotate(geom="text", x=16, y=0.02, label=" area = alpha", color="orchid4") +
  annotate(geom="text", x=4.5, y=0.04, label=" area = 1 - alpha", color="orchid4") +
  theme_bw()
```

