---
title: "STT 3820 R Scripts"
author: "Dr. Hasthika Rupasinghe"
date: 'Last compiled: `r format(Sys.time(), "%A, %B %d, %Y - %X.")`'
output:
  html_document:
    css: ../css/style.css
    highlight: textmate
    theme: yeti
---

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>


***


## Week 1: (Aug 16--20) {-}


* No R scripts are needed

***

## Week 2: (Aug 23--27) {-}

* [Intro R codes](../Lecture Notes/IntroR.html)
* [Intro R Homework](../Lecture Notes/IntroRHW.html)
* [Chapter 16 R codes](../Lecture Notes/Ch16_New_CI_proportions.html) - CI for $p$

***

## Week 3 (Aug 30--Sep 3) {-}

* [Chapter 16 R codes](../Lecture Notes/Ch16_New_CI_proportions.html) - CI for $p$

***

## Week 4 (Sep 06--Sep 10) {-}

* [Chapter 16 R codes](../Lecture Notes/Ch16_New_CI_proportions.html) - CI for $p$
* [Chapter 17 R codes](../Lecture Notes/Ch17_New_mean.html) - CI for $\mu$

***

## Week 5 (Sep 13--Sep 17) {-}


* [Chapter 17 R codes](../Lecture Notes/Ch17_New_mean.html) - CI for $\mu$
* [Chapter 18 R codes](../Lecture Notes/Ch18_New_HT_P_Mean.html) - HT for $p$ and HT for $\mu$

***

## Week 6 (Sep 20--Sep 24) {-}


* [Chapter 17 R codes](../Lecture Notes/Ch17_New_mean.html) - CI for $\mu$
* [Chapter 18 R codes](../Lecture Notes/Ch18_New_HT_P_Mean.html) - HT for $p$ and HT for $\mu$

***


## Week 7 (Sep 27--Oct 01) {-}

* [Chapter 20 R codes: PART I](../Lecture Notes/Ch20_New_CI_HT_two_p.html) - CI \& HT for $p_1 - p_2$
* [Chapter 20 R codes: PART II](../Lecture Notes/Ch20_New_CI_HT_two_means.html) -  CI and HT for $\mu_1 - \mu_2$

***

## Week 7 (Oct 04--Oct 08) {-}

* [Chapter 21 R codes](../Lecture Notes/Ch21_new_paired_data.html) - CI \& HT for 
 $\mu_d = \mu_1 - \mu_2$

***

## Week 8 (Oct 11--Oct 15) {-}

* [Chapter 21 R codes](../Lecture Notes/Ch21_new_paired_data.html) - CI \& HT for 
 $\mu_d = \mu_1 - \mu_2$
* Exam 1

***

## Week 9 (Oct 18--Oct 22) {-}

* **Mid Term Project** - Due Tuesday, Oct 26, by 4:00 p.m.
    * [Mid Term Project Description](../Lecture Notes/MidTermProjectDescription.pdf)
    
    * Data Files
      * [Student Debt Data File](../Lecture Notes/MEANSTUDENTLOANDEBTBYCATEGORY.CSV)
        * [Student Debt data description](../Lecture Notes/StudentDebt.pdf)
      
      * [Marriage and Divorce Data](../Lecture Notes/MarDiv2009.xls)
        * [No description for this data set]()
        
    * [Peer Evaluation Form](../Lecture Notes/PeerEval_Form_3820.pdf)

***



## Week 10: (Oct 25--29) {-}

* [R codes for Ch 22](../Lecture Notes/Ch22_new_chi_sq.html) - $\chi^2$ test for Comparing Counts

***


<!--
* [R codes for Ch 17 Proportions](../Lecture Notes/Ch17_proportions.html)
* [R codes for Ch 17 Means](../Lecture Notes/Ch17_mean.html)



## Week 4: (Feb 3--7) {-}

* [R codes for Ch 18](../Lecture Notes/Ch18.html)

## Week 5: (Feb 10--14) {-}

* [R codes for Ch 19](../Lecture Notes/Ch19.html)

## Week 6: (Feb 17--21) {-}

* [R codes for Ch 20](../Lecture Notes/Ch20.html)

## Week 7: (Feb 24--28) {-}

* No new R scripts are needed (for ch 21 use the previous scripts)

## Week 8: (Mar 2--6) {-}

* [R codes for Ch 22: Two Proportions](../Lecture Notes/Ch22.html)
* [R codes for Ch 22: Two Means](../Lecture Notes/Ch22_2.html)


## Week 9: (Mar 9--13) {-}

* [Exam 1 Grade Distribution](../Lecture Notes/GradesExam1.html)

* [R codes for Ch 23: Two Dependent Means](../Lecture Notes/Ch23.html)

* [**Lecture Video for Ch 23**](https://appstate.zoom.us/rec/share/-u5RcYOo9GdIH7fd8BDhWKoPM97saaa8gCgXrKJcn0v7yo6BGPkPIMvFJ3yvR_2u)

## Week 10: (Mar 23--27) {-}

* [R codes for Ch 24](../Lecture Notes/Ch24.html)

* [**Lecture Video for Ch 24 Part 1**](https://appstate.zoom.us/rec/share/5c0sIu7a2DpIaaPyym2HULY4NIXOeaa81CAfqPYPy08UanoEfAfTLa03ToZhjM_6)

## Week 11: (Mar 30-- Apr 4) {-}

* [**Lecture Video for Ch 24 Part 2**](https://appstate.zoom.us/rec/share/4JB6I7C38TxLAZ3guX3OB_8OH5zoT6a8gXMe_PZfyBps1H_G_gzW2VU0FVQ9eHxW)

* [R codes for Ch 25: With raw data](../Lecture Notes/Ch25.html)

* [**Lecture Video for Ch 25 Part 1**](https://appstate.zoom.us/rec/share/pvZSAZCr2kZIfLf82R2PR5d5MNu7T6a80SFL_vYKn0a6HQy4WXc95v9H_wLXghT0)


* [**Lecture Video for Ch 25 Part 2**](https://appstate.zoom.us/rec/share/-PAoD5j6rHNOUpHsq3-ESvNxOISiX6a80ChL-_dbzUwBbzOw4Sq-oqlgGvBINE-U)

* [**Lecture Video for Ch 25 Part 3**](https://appstate.zoom.us/rec/share/vMEsIr_p11JObs_HwWvefYF4QKq0X6a8hiQd_fMEnUlhk4OWhVMTvwkiPD_bj_e6)

* [R codes for Ch 25: With summary stats](../Lecture Notes/Ch25_2.html)


* Data for Ch 25: [Atlanta Regression](../Lecture Notes/AtlantaRegression.csv)


## Week 12: (Apr 7-- Apr 11) {-}

* [R codes for Ch 26](../Lecture Notes/Ch26.html)
* [Data for Ch 26](../Lecture Notes/ScoreACT.txt)

* [**Lecture Video for Ch 26 Part 1**](https://appstate.zoom.us/rec/share/-Jx7MprR_EJOTquU10P-VbA_R8fraaa8hCQW8vcNnUhZ-aO4jrfHPnN75P_fsTka)

* [**Lecture Video for Ch 26 Part 2**](https://appstate.zoom.us/rec/share/1OxcIvLtpzhOE43D62HwcPB7M77OT6a80SUcqPIMyUdv_zkS8ghLwwquu3rOWl-1)

* [**Review for test 2 - video recording**](https://appstate.zoom.us/rec/share/y85KD7GvpkNJTp3qsWuCUbYdL7nfX6a82iQZ8_VbyEwbTEfv_wGPTdmQurq9bTCY)


## Week 14: (Apr 27-- Apr 28) {-}

* [**Review for Final - video recording**](https://appstate.zoom.us/rec/share/1MUoNor0qGlJfZGTxmXEea8NDrT1eaa8hHVLqPpYnR7tV86QgKABDWptTRPkjftk)

-->
